### PR TITLE
fix: no bool coercion

### LINKED ISSUE #183: `Value::to_bool` should not exist?
Currently these expressions would succeeed:

```rust
    #[test]
    fn test_logical_ops_with_non_bools() {
        let program = Program::compile("[] && true").unwrap();
        // should be expected type 'bool' but found 'list(_var0)'
        assert!(program.execute(&Context::default()).is_err());

        let program = Program::compile("[] || true").unwrap();
        // should be expected type 'bool' but found 'list(_var0)'
        assert!(program.execute(&Context::default()).is_err());

        let program = Program::compile("{} && true").unwrap();
        // expected type 'bool' but found 'map(_var0, _var1)'
        assert!(program.execute(&Context::default()).is_err());

        let program = Program::compile("{} || true").unwrap();
        // expected type 'bool' but found 'map(_var0, _var1)'
        assert!(program.execute(&Context::default()).is_err());
    }
```

But I think they should _not_, as `&&` & `||` should only operate on boolean values, we currently have `Value::to_bool()` that coerces all possible values in a `boolean` value, which is afaict plainly wrong... 

## Not asking to fix this!

Tho we could, it's just an issue that came up while refactoring the interpreter to use an open type system (using a Rust `trait Val`), with its own traits and overloads, as per the spec. Mostly want to provide some transparency to the work that is on going and all the changes that may land as part of implementing the new, spec compliant (or at least hopefully more so) type system within the interpreter

### PR DESCRIPTION
**Pull request by alexsnaps**
fixes #183 

Changed my mind, as I'm having a hard time seeing where I'm at wrt traits & overloads, so fixing this on its own... tho the fix isn't correct per se, but still gets us closer to compliance...

### CODE REVIEW

**Comment by clarkmcc** [comment]
Sorry, just got back from traveling all last week.

> tho the fix isn't correct per se

Can you speak to this a bit more? What are the concerns with this PR that I should look at?

File: cel/src/objects.rs [hunk 1]
```diff
@@ -802,22 +802,13 @@ impl Value {
...
-            #[cfg(feature = "chrono")]
-            Value::Duration(v) => v.num_nanoseconds().map(|n| n != 0).unwrap_or(false),
-            #[cfg(feature = "chrono")]
-            Value::Timestamp(v) => v.timestamp_nanos_opt().unwrap_or_default() > 0,
-            Value::Function(_, _) => false,
+            Value::Bool(v) => Ok(*v),
+            _ => Err(ExecutionError::UnexpectedType {
+                got: self.type_of().to_string(),
+                want: ValueType::Bool.to_string(),
+            }),
```
Comment (alexsnaps) [inline cel/src/objects.rs]: I guess this is the "offending code". This should return a `Val` that represents an `Error` (a CEL one), that represents the `"no such overload"`

Comment (clarkmcc) [reply cel/src/objects.rs]: Why would we have CEL errors in the form of an error `Val`?

> There is no in-language representation of errors, no generic way to raise them, and no way to catch or bypass errors, except for the short-circuiting behavior of the logical operators, and macros. https://github.com/google/cel-spec/blob/master/doc/langdef.md#runtime-errors

Seems like `ExecutionError` works fine for terminating in the case of a 'no such overload' error doesn't it?

Comment (alexsnaps) [reply cel/src/objects.rs]: I'm actually slowly changing my mind about how other interpreters went about that indeed too... it'll probably be something more elaborate overtime than a `ExecutionError` (i.e. when caught at `check`-phase), but otherwise yes, I think I'll try refactor my code to have a proper `ExecutionError::NoSuchOverload` and see how that goes for these, and burn all `Type::Error`, `ERROR_TYPE` et al. 

Not that this changes anything _for this PR_ tho, does it? Or should I add this as part of this... Looks like it _could_ replace the `UnexpectedType` one actually 🤔

Comment (clarkmcc) [reply cel/src/objects.rs]: Yeah I think moving to `ExecutionError::NoSuchOverload` makes sense as part of this PR.

Side note, [why does this work](https://playcel.undistro.io/?content=H4sIAAAAAAAAA3VSTUsDQQz9K3E9VEFrPYiwN5GCStWiiAi9pLtpOzAfSybbD9T%2FbrJd0B5kL9l5L%2B%2B9TOazqMgXZXFxAe%2FkqxQIJIGsCG7HE5h63C05tbE%2BmkWlHJ6By4ARXBRirMStSTXmNzlTmPsdNGlDTDVQXDtOMVAU06Zt4xOTdtZWE7sO2ThZ7X1TCCnCeNsw5ey0nGBctrgkOFH%2F06El6dKcwzs7Idillrto9NuzUuue9JapE0YmBIWszq4mWCTW8E0rUKPgmdbwcfM4AT1%2BeH1%2BMjyg9CpTU4bBSxsH3RRr9C3%2BY45LdDFL5%2FRr0AuN%2B%2Fmtr0rek96c9qSFKmBoPOU%2BWG4co2Ez%2FbCq9MplOEePsSL4%2BlJWmsXirDDte3PRNR7DnQ5uizn0%2Fme24R%2FpchYBevkSrkYj%2B09r4ppxIVNOsk9agnBLB%2BDEBSclXI6sSRhjxj3VWLZYZW3Ql3BtBM2919DsIdWkse0Nfv8AQVPeO4sCAAA%3D) in CEL playground?

Comment (alexsnaps) [reply cel/src/objects.rs]: I found the same issue playing around indeed, if you change the operator to `&&`, it now fails with the expected `no such overload`. @adam-cattermole emitted the hypothesis, it's probably related to an optimization phase, where the expression _is always_ `true` (or `false`) based on either side, so the other isn't even evaluated, but _also not for correctness_. I think I'm buying the explanation and said I'd investigate it, but didn't come around to it yet. 

tl;dr I think it's a bug

Comment (alexsnaps) [reply cel/src/objects.rs]: Done!

**Comment by clarkmcc** [comment]
Hm... not sure why clippy is throwing a fit about lifetimes. Not sure why your changes would have impacted those. Can you review and let me know if there's just a problem with the build that I need to investigate?

**Comment by alexsnaps** [comment]
My bad, didn't even check what happened. I'll fix things. Could it be we don't pin the toolchain version & that's a new lint maybe?

**Comment by alexsnaps** [comment]
Right, passed with 1.88, but fails with 1.89 (which I _just_ updated to right now)

**Comment by alexsnaps** [comment]
And all green again :)

File: cel/src/functions.rs [hunk 2]
```diff
@@ -859,4 +850,20 @@ mod tests {
         .iter()
         .for_each(assert_script);
     }
+
+    #[test]
+    fn no_bool_coercion() {
+        // todo the real expected error here should be `no such overload`
```
[the remark this answers is not in the document]
Comment (clarkmcc) [reply cel/src/functions.rs]: @alexsnaps looks like an outdated comment.

**Review by clarkmcc — APPROVED** [review]
lgtm. One outdated comment
